=== ECAM-4MIN/Web-architecture/seance 2 - xsl/schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="recipe">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" ref="author"/>
                <xs:element minOccurs="0" ref="tags"/>
                <xs:element ref="image"/>
                <xs:element ref="content"/>
            </xs:sequence>
            <xs:attribute name="title" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="author" type="xs:string"/>
    <xs:element name="tags">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="tag"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="tag" type="xs:string"/>
    <xs:element name="image">
        <xs:complexType>
            <xs:attribute name="link" type="xs:string" use="required"></xs:attribute>
        </xs:complexType>
    </xs:element>
    <xs:element name="content">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" ref="introduction"/>
                <xs:element ref="ingredients"/>
                <xs:element ref="realisation"/>
                <xs:element ref="direction"/>
                <xs:element minOccurs="0" ref="dietetic"/>
                <xs:element minOccurs="0" ref="tricks"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="introduction" type="xs:string"/>
    <xs:element name="ingredients">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="item"/>
            </xs:sequence>
            <xs:attribute name="quantity" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:integer">
                        <xs:minInclusive value="1" />
                        <xs:maxInclusive value="20" />
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
    <xs:element name="item" type="xs:string"/>
    <xs:element name="realisation">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" ref="difficulty"/>
                <xs:element ref="preparation"/>
                <xs:element ref="cooking"/>
                <xs:element minOccurs="0" ref="total_time"/>
                <xs:element minOccurs="0" ref="score"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="difficulty" type="xs:string"/>
    <xs:element name="preparation">       
        <xs:complexType mixed="true">

            <xs:attribute name="unit" use="required" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="cooking">
        <xs:complexType mixed="true">
            <xs:attribute name="unit" use="required" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="total_time">
        <xs:complexType mixed="true">
            <xs:attribute name="unit" use="required" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="score" type="xs:string"/>
    <xs:element name="direction">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="step"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="step">
        <xs:complexType mixed="true">
            <xs:attribute name="num" type="xs:integer"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="dietetic" type="xs:string"/>
    <xs:element name="tricks" type="xs:string"/>
</xs:schema>

=== ECAM-4MIN/Web-architecture/seance 2 - xsl/Recipe1.XML
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="stylesheet.xsl"?>
<recipe title="Recette Soufflé léger au chou-fleur" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./schema.xsd">
    <author>Isabelle Bonneau</author>
    <image link="img/soufflé.jpg"></image>
    <content>
        <introduction>
            Ce soufflé est très facile à réaliser, très léger et moelleux, un bon accompagnement pour viandes et poissons !
        </introduction>
        <ingredients quantity="4">
            <item>600 g de chou-fleur</item>
            <item>200 g de fromage blanc à 20%</item>
            <item>40 g de fromage rapé</item>
            <item>2 oeufs</item>
            <item>noix de muscade fraichement rapée</item>
            <item>sel</item>
            <item>poivre</item>
        </ingredients>
        <realisation>
            <difficulty>Facile</difficulty>
            <preparation unit="min">20</preparation> 
            <cooking unit="min">40</cooking>
            <total_time unit="h">1</total_time>
        </realisation>
        <direction>
            <step num="1">
                Faites cuire le chou-fleur à la vapeur après l'avoir lavé. Préchauffez votre four à 180°C.
            </step>
            <step num="2">
                Séparez les blancs des jaunes d'oeufs. Mixez le chou-fleur avec les jaunes et le fromage blanc. Salez, poivrez et ajouter la noix de muscade ainsi que le fromage rapé.
            </step>
            <step num="3">
                Montez les blancs d'oeufs en neige et incorporez les délicatement au chou-fleur.
            </step>
            <step num="4">
                Versez le tout dans un plat allant au four ou 4 petits plats individuels et faites cuire au four à 180°C entre 25 et 30 minutes. N'ouvrez surtout pas la porte du four avant la fin de la cuisson, le soufflé retomberait !
            </step>
            <step>
                Servez chaud dès que le dessus est doré.
            </step>
        </direction>
    </content>
</recipe>

=== ECAM-4MIN/Web-architecture/seance 2/Recipe2.XML
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="stylesheet.xsl"?>
<recipe title="Fondant au chocolat ultra facile" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./schema.xsd">
    <tags>
        <tag>Dessert</tag>
        <tag>Facile</tag>
        <tag>Bon marché</tag>
        <tag>Végétarien</tag>
    </tags>
    <image link="img/choco.jpg"></image>
    <content>
        
        <ingredients quantity="6">
            <item>600 g de chocolat</item>
            <item>200 g de sucre</item>
            <item>8 oeufs</item>
        </ingredients>
        <realisation>
            <preparation unit="min">5</preparation> 
            <cooking unit="min">7</cooking>
        </realisation>
        <direction>
            <step>
                Préchauffer le four à 210°C (thermostat 7)
            </step>
            <step>
                Faire fondre le chocolat au bain-marie
            </step>
            <step>
                Pendant ce temps, mélanger les oeufs, le sucre et faire blanchir
            </step>
            <step>
                Quand le chocolat est fondu, l'incorporer au mélange oeufs et sucre
            </step>
            <step>
                Beurrer un moule à manqué ou des moules individuels (de préférence en silicone) et y verser la préparation
            </step>
            <step>
                Faire cuire le fondant pendant environ 7 à 10 minutes
            </step>
            <step>
                Attention, vérifier la cuisson en plantant la pointe du couteau au milieu du fondant.
            </step>

        </direction>
    </content>
    
</recipe>

=== ECAM-4MIN/Web-architecture/seance 2/Recipe3.XML
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="stylesheet.xsl"?>
<recipe title="Pâte à crêpes simple et rapide" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./schema.xsd">
    <image link="img/crepe.jpg"></image>
    <content>
        <introduction>
            À la fête de la Chandeleur ou au Mardi Gras, la tradition veut que l'on fasse des crêpes. 
            En Bretagne, les crêpes font parties de la culture locale et se consomment très souvent sucrées avec de la farine de froment ou salées avec de la farine de blé noir. 
            Seulement voilà, pas de bonnes crêpes sans une bonne pâte à crêpes simple et rapide à faire ! La recette de crêpe fera plaisir à tous les gourmands et les bouches sucrées 
        </introduction>
        <ingredients quantity="4">
            <item>1/2 l de lait</item>
            <item>3 oeufs</item>
            <item>250 g de farine</item>
            <item>2 c. à soupe d'huile</item>
            <item>1 pincée de sel</item>
            <item>1 ou 2 c. à soupe d'eau</item>
        </ingredients>
        <realisation>
            <difficulty>Facile</difficulty>
            <preparation unit="min">15</preparation> 
            <cooking unit="min">20</cooking>
            <total_time unit="h">1</total_time>
            <score>7,93</score>
            
        </realisation>
        <direction>
            <step num="1">
                Mettez la farine dans un grand saladier ou cul de poule. Faites un puits, et cassez-y les oeufs entiers.
            </step>
            <step num="2">
                Ajoutez l'huile, le sel et un peu de lait. Travaillez énergiquement la pâte avec une cuillère (en bois, de préférence), pour la rendre légère.
            </step>
            <step num="3">
                Mouillez progressivement avec le lait, jusqu'à ce que la pâte devienne homogène.
            </step>
            <step num="4">
                Vous pouvez alors ajouter de l'extrait de fleur d'oranger, un peu de jus de citron, de la vanille, etc.
            </step>
            <step num="5">
                Ajoutez ensuite 1 à 2 c. à soupe d'eau.
            </step>
            <step num="6">
                Laissez reposer la pâte à crêpes simple et rapide à faire pendant 1 heure au moins, recouverte d'une serviette ou d'un chiffon propre.
            </step>
            <step num="7">
                Versez une louche de pâte dans la poêle, et laissez cuire 3 min chaque crêpe.
            </step>
        </direction>
        <dietetic>
            Valeur nutritionnelle pour 100g : 300 kcal
        </dietetic>
        <tricks>
            Il existe plusieurs recettes de pâte à crêpes simple et rapide, sucrées ou salées, qui plairont à tous. 
            La pâte à crêpes est une base assez simple, il suffit de l'agrémenter selon vos envies : crêpe suzette, crêpe au sarrasin ou simplement crêpe au chocolat ou crêpe au beurre. 
            Dans la plus pure tradition, nous vous conseillons de manger vos crêpes accompagnées de cidre brut.
        </tricks>

    </content>
</recipe>
