=== ECAM-4MIN/Web-architecture/seance 1/Recipe.dtd
<!ELEMENT recipe (author?,tags?,content)>
<!ATTLIST recipe title CDATA #REQUIRED>
<!ELEMENT author (#PCDATA)>
<!ELEMENT tags (tag+)>
<!ELEMENT tag (#PCDATA)>
<!ELEMENT content (introduction?,ingredients,realisation,direction,dietetic?,tricks?)>
<!ELEMENT introduction (#PCDATA)>
<!ELEMENT ingredients (item+)>
<!ATTLIST ingredients quantity NMTOKEN #REQUIRED>
<!ELEMENT item (#PCDATA)>
<!ELEMENT realisation (difficulty?,preparation,cooking,total_time?,score?)>
<!ELEMENT difficulty (#PCDATA)>
<!ELEMENT preparation (#PCDATA)>
<!ATTLIST preparation unit NMTOKEN #REQUIRED>
<!ELEMENT cooking (#PCDATA)>
<!ATTLIST cooking unit NMTOKEN #REQUIRED>
<!ELEMENT total_time (#PCDATA)>
<!ATTLIST total_time unit NMTOKEN #REQUIRED>
<!ELEMENT score (#PCDATA)>
<!ELEMENT direction (step+)>
<!ELEMENT step (#PCDATA)>
<!ATTLIST step num NMTOKEN #IMPLIED>
<!ELEMENT dietetic (#PCDATA)>
<!ELEMENT tricks (#PCDATA)>

=== ECAM-4MIN/Web-architecture/seance 1 - xml/Recipe2.XML
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE recipe SYSTEM "Recipe.dtd">
<recipe title="Fondant au chocolat ultra facile">
    <tags>
        <tag>Dessert</tag>
        <tag>Facile</tag>
        <tag>Bon marché</tag>
        <tag>Végétarien</tag>
    </tags>
    <content>
        
        <ingredients quantity="6">
            <item>600 g de chocolat</item>
            <item>200 g de sucre</item>
            <item>8 oeufs</item>
        </ingredients>
        <realisation>
            <preparation unit="min">5</preparation> 
            <cooking unit="min">7</cooking>
        </realisation>
        <direction>
            <step>
                Préchauffer le four à 210°C (thermostat 7)
            </step>
            <step>
                Faire fondre le chocolat au bain-marie
            </step>
            <step>
                Pendant ce temps, mélanger les oeufs, le sucre et faire blanchir
            </step>
            <step>
                Quand le chocolat est fondu, l'incorporer au mélange oeufs et sucre
            </step>
            <step>
                Beurrer un moule à manqué ou des moules individuels (de préférence en silicone) et y verser la préparation
            </step>
            <step>
                Faire cuire le fondant pendant environ 7 à 10 minutes
            </step>
            <step>
                Attention, vérifier la cuisson en plantant la pointe du couteau au milieu du fondant.
            </step>

        </direction>
    </content>
    
</recipe>
